---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.202.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: cli/cli@v2.52.0
- name: editorconfig-checker/editorconfig-checker@v3.0.3
- name: jqlang/jq@jq-1.7.1
- name: google/yamlfmt@v0.13.0
- name: go-task/task@v3.38.0
- name: securego/gosec@v2.20.0
- name: aquasecurity/trivy@v0.53.0
- name: dominikh/go-tools/staticcheck@2023.1.7
- name: Songmu/tagpr@v1.3.0
- name: suzuki-shunsuke/ghalint@v0.2.12
- name: rhysd/actionlint@v1.7.1
