---
formatter:
  type: basic
  include_document_start: true
  line_ending: lf
  retain_line_breaks: true
  retain_line_breaks_single: true
  indentless_arrays: true
  trim_trailing_whitespace: true
  eof_newline: true
